### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by scheung38** [geordgez/flask-s2i#7]
Why do we need to move files around for s2i to work?

Is this the reason why after building I get flask ModuleNotFoundError?

**Comment by geordgez** [comment]
Can I get more details? When you ask about moving files around, I'm guessing you are asking why the folder needs to be renamed to something ending in `-app`; is that correct?

I haven't touched `s2i` in a while. But renaming the folder and creating the `.s2i/environment` file were the only two steps I needed to figure out to get a simple Flask app running.

**Comment by scheung38** [comment]
Hi 

Can I ask you what is the build image size from s2i ? I used 

docker pull registry.access.redhat.com/ubi8/python-36

s2i build <my flask starter repo> registry.access.redhat.com/ubi8/python-36 my-flask-sample-app

but docker images show

753MB size

is this what you expected? Such a large image for a Flask start app?

**Comment by geordgez** [comment]
EDIT: I do recall the final output image being quite large. I never dug into it, but you can probably tune the output image based on the docs: https://docs.openshift.com/container-platform/3.5/using_images/s2i_images/customizing_s2i_images.html

---

Keep in mind that your builder image typically isn't the same as your prod / deployed image; `s2i` should output another image which is optimized to only run your specific functionality. Your builder images may be very large as they include dev helper libraries. 

As a side note related to a different aspect of image sizes, Python images are generally large anyways due to its interpreted nature. Still, you could try to use an alpine-based image with the final deployment if you are really trying to optimize image size at that point.

**Comment by geordgez** [comment]
Also, I'll close this as you're probably getting better answers from https://github.com/sclorg/s2i-python-container/issues/334

**Comment by scheung38** [comment]
Any idea what is the --context-dir does? A bit confused why it is needed.

s2i create <imageName> <destination> but this seems to generate a rubygems install and we need to manually edit the Dockerfile? Also any other edits needed within the assemble, run etc files?
